package org.gromurph.javascore;

public class JavaScoreVersion 
{
	public static final String RELEASE = "20150301";
    public static final String VERSION = "7.3";
// auto generated by the build script
}
